import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import Providers from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "W2G",
    description: "Generated by create next app",
    icons: {
        icon: "/Logo.png",
        shortcut: "/Logo.png",
        apple: "/Logo.png",
    },
};

/**
 * The root layout component that wraps the entire app.
 * It includes the header and footer components, as well as the StyledComponentsRegistry and Providers components.
 * @param {ReactNode} children - The children elements to be rendered inside the app.
 * @returns {JSX.Element} - The root layout element.
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <StyledComponentsRegistry>
                    <Providers>
                        <Suspense fallback={null}>
                            <Header />
                        </Suspense>
                        {children}
                        <Footer />
                    </Providers>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
